FROM golang:1.20-bullseye

# Cài ffmpeg
RUN apt-get update && apt-get install -y ffmpeg curl

# Cài yt-dlp
RUN curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp \
    && chmod +x /usr/local/bin/yt-dlp

WORKDIR /app
COPY . .
RUN go build -o bot main.go

CMD ["./bot"]
